/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pbolastproject;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Doddy Prayogo
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */

    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textPengguna = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        passwordPengguna = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        backGround1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CINEMAX");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(150, 10, 83, 22);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Doddy Prayogo\\Pictures\\Saved Pictures\\png-clipart-computer-icons-user-login-gender-miscellaneous-desktop-wallpaper1.png")); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(90, 40, 50, 50);
        jPanel1.add(textPengguna);
        textPengguna.setBounds(151, 56, 155, 22);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Doddy Prayogo\\Pictures\\Saved Pictures\\PASSWORD.png")); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(90, 130, 50, 50);
        jPanel1.add(passwordPengguna);
        passwordPengguna.setBounds(150, 140, 155, 22);

        jButton1.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jButton1.setText("LOGIN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(140, 220, 114, 24);

        backGround1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Doddy Prayogo\\Pictures\\Saved Pictures\\studio-1-bioskop-movimax.jpg")); // NOI18N
        jPanel1.add(backGround1);
        backGround1.setBounds(0, 0, 390, 370);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         if (textPengguna.getText().isEmpty() && new String(passwordPengguna.getPassword()).isEmpty()) {
            JOptionPane.showMessageDialog(this, "Isi Data Terlebih Dahulu!", "Form Tidak Boleh Kosong", JOptionPane.WARNING_MESSAGE);
        } else if (new String(passwordPengguna.getPassword()).isEmpty()) {
            JOptionPane.showMessageDialog(this, "Masukkan Password Terlebih Dahulu", "Form Password Tidak Boleh Kosong", JOptionPane.WARNING_MESSAGE);
        } else if (textPengguna.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Isi Pengguna Terlebih Dahulu!", "Form Pengguna Tidak Boleh Kosong", JOptionPane.WARNING_MESSAGE);
        } else {
            ResultSet rs = null;
            Statement stmt = null;
            Connection conn = null;
            try {
                String username = textPengguna.getText();
                String password = new String(passwordPengguna.getPassword());
                conn = Conn.getConnection(); // Menggunakan kelas Conn untuk mendapatkan koneksi
                stmt = conn.createStatement();
                rs = stmt.executeQuery("SELECT * FROM user WHERE username = '" + username + "' AND password = '" + password + "'");
                if (rs.next()) {
                    JOptionPane.showMessageDialog(this, "Login Berhasil!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                    Movie movie = new Movie();
                    movie.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(this, "Kombinasi Pengguna dan Kata Sandi tidak cocok.", "Login Gagal", JOptionPane.ERROR_MESSAGE);
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Database connection error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            } finally {
                try {
                    if (rs != null) rs.close();
                    if (stmt != null) stmt.close();
                    if (conn != null) conn.close();
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(this, "Error closing resources: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backGround1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField passwordPengguna;
    private javax.swing.JTextField textPengguna;
    // End of variables declaration//GEN-END:variables
}
